services:
  user-service:
    image: users:v1
    networks: [micro-net]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  order-service:
    image: orders:v1
    environment:
      - USER_SERVICE_URL=http://user-service:3001
    networks: [micro-net]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  api-gateway:
    image: gateway:v1
    networks: [micro-net]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx-proxy:v1
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks: [micro-net]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  micro-net:
    driver: overlay
